apiVersion: v1
kind: ConfigMap
metadata:
  name: erp-uno-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "erp-uno.labels" . | nindent 4 }}
data:
  DOMAIN: {{ .Values.global.domain }}
  ENVIRONMENT: {{ .Values.global.environment }}
  REGISTRY: {{ .Values.global.registry }}
  VERSION: {{ .Values.global.version }}
