---
# Grafana with emptyDir (temporary storage for demo)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-demo
  namespace: {{ $.Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-demo
  template:
    metadata:
      labels:
        app: grafana-demo
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:11.1.0
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: admin
        - name: GF_SECURITY_ADMIN_USER
          value: admin
        volumeMounts:
        - name: storage
          mountPath: /var/lib/grafana
      volumes:
      - name: storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-demo
  namespace: {{ $.Values.namespace }}
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: grafana-demo
